// flow-typed signature: d43b6460048ba07cf9c6427f392902bf
// flow-typed version: <<STUB>>/ramda-lens_vgit+https://github.com/al-zah/ramda-lens#a05272d999375b9de2b9efb2b43640f502a6c84a/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ramda-lens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ramda-lens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ramda-lens/src/folds' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/internal/_const' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/internal/_identity' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/internal/_monoids' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/isos' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/lens' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/over' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/traversals' {
  declare module.exports: any;
}

declare module 'ramda-lens/src/view' {
  declare module.exports: any;
}

declare module 'ramda-lens/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ramda-lens/index' {
  declare module.exports: $Exports<'ramda-lens'>;
}
declare module 'ramda-lens/index.js' {
  declare module.exports: $Exports<'ramda-lens'>;
}
declare module 'ramda-lens/src/folds.js' {
  declare module.exports: $Exports<'ramda-lens/src/folds'>;
}
declare module 'ramda-lens/src/internal/_const.js' {
  declare module.exports: $Exports<'ramda-lens/src/internal/_const'>;
}
declare module 'ramda-lens/src/internal/_identity.js' {
  declare module.exports: $Exports<'ramda-lens/src/internal/_identity'>;
}
declare module 'ramda-lens/src/internal/_monoids.js' {
  declare module.exports: $Exports<'ramda-lens/src/internal/_monoids'>;
}
declare module 'ramda-lens/src/isos.js' {
  declare module.exports: $Exports<'ramda-lens/src/isos'>;
}
declare module 'ramda-lens/src/lens.js' {
  declare module.exports: $Exports<'ramda-lens/src/lens'>;
}
declare module 'ramda-lens/src/over.js' {
  declare module.exports: $Exports<'ramda-lens/src/over'>;
}
declare module 'ramda-lens/src/traversals.js' {
  declare module.exports: $Exports<'ramda-lens/src/traversals'>;
}
declare module 'ramda-lens/src/view.js' {
  declare module.exports: $Exports<'ramda-lens/src/view'>;
}
declare module 'ramda-lens/test/test.js' {
  declare module.exports: $Exports<'ramda-lens/test/test'>;
}
