// flow-typed signature: 3fb735a04be281a7923594f541ef7634
// flow-typed version: <<STUB>>/redux-ntities_v^0.0.8/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-ntities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-ntities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-ntities/flowtype/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/api/cache' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/api/fetch' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/hoc/fetcher/actions' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/hoc/fetcher/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/hoc/fetcher/reducer' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/hoc/sync/actions' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/hoc/sync/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/internal/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/middleware/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/lib/reducer/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/api/cache' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/api/fetch' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/hoc/fetcher/actions' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/hoc/fetcher/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/hoc/sync/actions' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/hoc/sync/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/internal/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/middleware/index' {
  declare module.exports: any;
}

declare module 'redux-ntities/src/reducer/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-ntities/flowtype/index.js' {
  declare module.exports: $Exports<'redux-ntities/flowtype/index'>;
}
declare module 'redux-ntities/lib/api/cache.js' {
  declare module.exports: $Exports<'redux-ntities/lib/api/cache'>;
}
declare module 'redux-ntities/lib/api/fetch.js' {
  declare module.exports: $Exports<'redux-ntities/lib/api/fetch'>;
}
declare module 'redux-ntities/lib/hoc/fetcher/actions.js' {
  declare module.exports: $Exports<'redux-ntities/lib/hoc/fetcher/actions'>;
}
declare module 'redux-ntities/lib/hoc/fetcher/index.js' {
  declare module.exports: $Exports<'redux-ntities/lib/hoc/fetcher/index'>;
}
declare module 'redux-ntities/lib/hoc/fetcher/reducer.js' {
  declare module.exports: $Exports<'redux-ntities/lib/hoc/fetcher/reducer'>;
}
declare module 'redux-ntities/lib/hoc/sync/actions.js' {
  declare module.exports: $Exports<'redux-ntities/lib/hoc/sync/actions'>;
}
declare module 'redux-ntities/lib/hoc/sync/index.js' {
  declare module.exports: $Exports<'redux-ntities/lib/hoc/sync/index'>;
}
declare module 'redux-ntities/lib/index.js' {
  declare module.exports: $Exports<'redux-ntities/lib/index'>;
}
declare module 'redux-ntities/lib/internal/index.js' {
  declare module.exports: $Exports<'redux-ntities/lib/internal/index'>;
}
declare module 'redux-ntities/lib/middleware/index.js' {
  declare module.exports: $Exports<'redux-ntities/lib/middleware/index'>;
}
declare module 'redux-ntities/lib/reducer/index.js' {
  declare module.exports: $Exports<'redux-ntities/lib/reducer/index'>;
}
declare module 'redux-ntities/src/api/cache.js' {
  declare module.exports: $Exports<'redux-ntities/src/api/cache'>;
}
declare module 'redux-ntities/src/api/fetch.js' {
  declare module.exports: $Exports<'redux-ntities/src/api/fetch'>;
}
declare module 'redux-ntities/src/hoc/fetcher/actions.js' {
  declare module.exports: $Exports<'redux-ntities/src/hoc/fetcher/actions'>;
}
declare module 'redux-ntities/src/hoc/fetcher/index.js' {
  declare module.exports: $Exports<'redux-ntities/src/hoc/fetcher/index'>;
}
declare module 'redux-ntities/src/hoc/sync/actions.js' {
  declare module.exports: $Exports<'redux-ntities/src/hoc/sync/actions'>;
}
declare module 'redux-ntities/src/hoc/sync/index.js' {
  declare module.exports: $Exports<'redux-ntities/src/hoc/sync/index'>;
}
declare module 'redux-ntities/src/index.js' {
  declare module.exports: $Exports<'redux-ntities/src/index'>;
}
declare module 'redux-ntities/src/internal/index.js' {
  declare module.exports: $Exports<'redux-ntities/src/internal/index'>;
}
declare module 'redux-ntities/src/middleware/index.js' {
  declare module.exports: $Exports<'redux-ntities/src/middleware/index'>;
}
declare module 'redux-ntities/src/reducer/index.js' {
  declare module.exports: $Exports<'redux-ntities/src/reducer/index'>;
}
